package it.course.myblog.entity;

public enum RoleName {
	
	ROLE_ADMIN,
	ROLE_EDITOR,
	ROLE_MANAGING_EDITOR,
	ROLE_READER
	
	/**
	 * 	ROLE_ADMIN:           MANAGE DATABASE & Application
	 *  ROLE_EDITOR:          CREATE, UPDATE, UNPUBLISH, PUBLISH POSTS; CENSOR COMMENTS
	 * 	ROLE_MANAGING_EDITOR  UNPUBLISH, PUBLISH POSTS; CENSOR COMMENTS
	 * 	ROLE_READER:          READ POSTS & CREATE, UPDATE, DELETE OWN COMPONENTS, RATE POSTS
	 */
//	

}
